services:
  asciidoctor-base: &asciidoctor-base
    image: asciidoctor/docker-asciidoctor:1.83
    user: ${CURRENT_UID}
    volumes:
      - ./src:/documents
      - ./dist:/dist

  html:
    <<: *asciidoctor-base
    command: >
      asciidoctor /documents/index.adoc
      -a cv-url="${CV_URL}"
      -a source-url="${SOURCE_URL}"
      -a short-owner-name="${SHORT_OWNER_NAME}"
      -a toc=left
      -a toclevels=2
      -o /dist/index.html

  pdf:
    <<: *asciidoctor-base
    command: >
      asciidoctor-pdf /documents/index.adoc 
      -a cv-url="${CV_URL}"
      -a source-url="${SOURCE_URL}"
      -a short-owner-name="${SHORT_OWNER_NAME}"
      -o /dist/cv-"${SHORT_OWNER_NAME}".pdf
