name: CV Generation and Deployment

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'docker-compose.yml'
      - '.github/workflows/cv-gh_pages.yml'
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Update CV from AsciiDoctorGenerator manually'
        required: false
        default: 'Update CV from AsciiDoctorGenerator'

permissions:
  contents: read

env:
  REPOSITORY_OWNER: roybaptiste
  SHORT_OWNER_NAME: "roy-baptiste"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build CVs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dist directories
        run: mkdir -p dist/cv/css dist/en/css

      - name: Copy static files
        run: |
          cp src/index.html dist/index.html
          cp src/css/custom.css dist/cv/css/custom.css
          cp src/css/custom.css dist/en/css/custom.css
      
      - name: Generate French HTML
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor src/index.adoc -a lang=fr -D dist/cv -o index.html"

      - name: Generate English HTML
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor src/index.adoc -a lang=en -D dist/en -o index.html"

      - name: Generate French PDF
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf src/index.adoc -a lang=fr -D dist/cv -o cv-${{ env.SHORT_OWNER_NAME }}-fr.pdf"
      
      - name: Generate English PDF
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf src/index.adoc -a lang=en -D dist/en -o cv-${{ env.SHORT_OWNER_NAME }}-en.pdf"

      - name: Upload CV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-build
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    permissions:
      contents: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PAGES_IO_DEPLOY }}
      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_OWNER }}.github.io
          ssh-key: ${{ secrets.PAGES_IO_DEPLOY }}
          fetch-depth: 1

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: cv-build
          path: .

      - name: Commit and push to target repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          COMMIT_MESSAGE="${{ github.event.inputs.deploy_message || 'Update CV from AsciiDoctorGenerator' }}"
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"
          git push