name: CV Generation and Deployment

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - '.github/workflows/cv-gh_pages.yml'
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Message personnalisé pour le déploiement'
        required: false
        default: 'Update CV from AsciiDoctorGenerator'

permissions:
  contents: read

env:
  REPOSITORY_OWNER: roybaptiste
  SHORT_OWNER_NAME: "roy-baptiste"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build CV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/asciidoctor
          key: ${{ runner.os }}-asciidoctor-${{ hashFiles('src/**') }}
          restore-keys: |
            ${{ runner.os }}-asciidoctor-

      - name: Create dist directory and copy resources
        run: |
          mkdir -p dist/images dist/css
          cp -r src/images/* dist/images/ || true
          cp src/css/custom.css dist/css/ || true

      - name: Generate HTML
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D dist --backend=html5 -o index.html -a toc2 src/index.adoc"

      - name: Upload CV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-build
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    permissions:
      contents: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PAGES_IO_DEPLOY }}
      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_OWNER }}.github.io
          ssh-key: ${{ secrets.PAGES_IO_DEPLOY }}
          fetch-depth: 1

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: cv-build
          path: downloaded-artifacts

      - name: Prepare cv directory
        run: |
          mkdir -p cv
          cp -r downloaded-artifacts/* cv/
          rm -rf downloaded-artifacts

      - name: Commit and push to target repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add cv
          COMMIT_MESSAGE="${{ github.event.inputs.deploy_message || 'Update CV from AsciiDoctorGenerator' }}"
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"
          git push