name: CV Generation and Deployment

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REPOSITORY_OWNER: roybaptiste
  SHORT_OWNER_NAME: "roy-baptiste"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy CV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist directory and copy resources
        run: |
          mkdir -p dist/images dist/css
          cp -r src/images/* dist/images/ || true
          cp src/css/custom.css dist/css/ || true

      - name: Generate HTML
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D dist --backend=html5 -o index.html -a toc2 src/index.adoc"

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: roybaptiste/roybaptiste.github.io
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gh-pages

      - name: Prepare cv directory in target repo
        run: |
          mkdir -p gh-pages/cv/css gh-pages/cv/images
          cp dist/index.html gh-pages/cv/index.html
          cp -r dist/css/* gh-pages/cv/css/ || true
          cp -r dist/images/* gh-pages/cv/images/ || true

      - name: Commit and push to target repository
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add cv
          git commit -m "Update CV from AsciiDoctorGenerator" || true
          git push